name: Distribution Builds

on:
  pull_request:
    types:
      - closed
jobs:
  build:
    env:
      ITCH_PROJECT: 'sandramoen/libgdx-jam-28'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: jdno/setup-butler@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: html:dist
      - name: Deploy 🚀
        run: butler push html/build/dist $ITCH_PROJECT:html
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
